import Head from "next/head";
import Layout from "@/components/layout";
import Card from "@/components/card";
import styles from "@/styles/Home.module.css";
import { getPosts } from "@/utils/posts";

export default function Home({ listData }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link
					rel="icon"
					href="/favicon.ico"
				/>
			</Head>
			<main className={styles.main}>
				<Layout>
					<h1>Lista Post</h1>
					{listData?.map((post, index) => (
						<Card
							key={index}
							post={post}
						/>
					))}
				</Layout>
			</main>
		</>
	);
}

export const getStaticProps = () => {
	const listData = getPosts();

	return {
		props: {
			listData,
		},
	};
};
