export const postsJson = [
	[
		{
			id: 1,
			title: "code 1",
			slug: "jedi-code-1",
			body: "There is no emotion there is peace",
			date: "22-01-2023",
			image: "https://picsum.photos/200/300?random=1",
		},
		{
			id: 2,
			title: "code 2",
			slug: "jedi-code-2",
			body: "There is no ignorance, there is knowledge",
			date: "28-01-2023",
			image: "https://picsum.photos/200/300?random=2",
		},
		{
			id: 3,
			title: "code 3",
			slug: "jedi-code-3",
			body: "There is no passion, there is serenity",
			date: "04-02-2023",
			image: "https://picsum.photos/200/300?random=3",
		},
		{
			id: 4,
			title: "code 4",
			slug: "jedi-code-4",
			body: "There is no chaos, there is harmony",
			date: "10-02-2023",
			image: "https://picsum.photos/200/300?random=4",
		},
		{
			id: 5,
			title: "code 5",
			slug: "jedi-code-5",
			body: "There is no death, there is the force",
			date: "10-02-2023",
			image: "https://picsum.photos/200/300?random=5",
		},
		{
			id: 6,
			title: "code 6",
			slug: "sith-code-1",
			body: "Peace is a lie, there is only passion",
			date: "12-02-2023",
			image: "https://picsum.photos/200/300?random=6",
		},
		{
			id: 7,
			title: "code 7",
			slug: "sith-code-2",
			body: "Through Passion, i gain Strenght",
			date: "16-02-2023",
			image: "https://picsum.photos/200/300?random=7",
		},
		{
			id: 8,
			title: "code 8",
			slug: "sith-code-3",
			body: "Through Strenght, i gain Power",
			date: "18-02-2023",
			image: "https://picsum.photos/200/300?random=8",
		},
		{
			id: 9,
			title: "code 9",
			slug: "sith-code-4",
			body: "Through Power, i gain Victory",
			date: "24-02-2023",
			image: "https://picsum.photos/200/300?random=9",
		},
		{
			id: 10,
			title: "code 10",
			slug: "sith-code-5",
			body: "Through Victory, my chains are Broken",
			date: "01-03-2023",
			image: "https://picsum.photos/200/300?random=10",
		},
		{
			id: 11,
			title: "code 11",
			slug: "sith-code-6",
			body: "The Force shall free me",
			date: "01-03-2023",
			image: "https://picsum.photos/200/300?random=11",
		},
	],
];
